### ISSUE TITLE
Import theme

### ISSUE THREAD

**Issue by elinkx-rko** [bareynol/mui-theme-creator#15]
Hi Brian,
great work!

I was wondering if it would possible to add _Import theme_ feature or simply allow copy-pasting into the source-code editor. The Editor appears to be read-only. 

Would be great to be able to adjust existing theme with your awesome app.

**Comment by mwiede** [comment]
as far as I can see, you can paste your ThemeOptions object into the editor.

**Comment by elinkx-rko** [comment]
@mwiede You are right, thank you! 

Maybe it's worth mentioning that the only editable part within editor area is in fact the **contents of theme object** (i.e. between curly braces). Typing/pasting anywhere else has no effect. Makes sense, of course.
